### ISSUE TITLE
env.reset(seed) is not fixing the static environment?

### ISSUE THREAD

**Issue by Mgineer117** [Tran-Research-Group/gym-multigrid#85]
Hi, after implementing my FourRoom according to the manual, I noticed that fixing the seed via the reset method does not statically define the grid. After carefully comparing my code to the original gym, I started to assume this may be attributed to the general Multigrid class. Does anyone have an idea on this?

**Comment by miki-yuasa** [comment]
I was looking at your code [here](https://github.com/Tran-Research-Group/gym-multigrid/blob/73edb163227af224d2715e70122c96c5357860c1/gym_multigrid/envs/fourrooms.py#L157). If this is the right location, my guess is the method doesn't call `super().reset(seed=seed)` to pass the seed to the RNG. There may be other reasons

**Comment by Mgineer117** [comment]
@miki-yuasa Hi! I completely forgot about the ticket I created. Thanks for the response Miki but I think that does not fix the issue. The code you were seeing is my trace to fix the seed anyhow after knowing ```super().reset(seed=seed)``` did not resolve the issue. Would you please be able to take a closer look to this? I am attaching what I observed below tho with one fixed seed:

![Screenshot from 2024-09-17 17-10-58](https://github.com/user-attachments/assets/988d1704-89be-4d1a-9013-b065e8031214)
![Screenshot from 2024-09-17 17-11-02](https://github.com/user-attachments/assets/7edf5d88-03a0-4233-980a-00a7da954eab)
![Screenshot from 2024-09-17 17-11-05](https://github.com/user-attachments/assets/34f1c93d-6603-4097-a43b-0d7ea2deab63)

**Comment by miki-yuasa** [comment]
I was looking into `self._rand_int` you are using to generate the door position. According to the line here, https://github.com/Tran-Research-Group/gym-multigrid/blob/73edb163227af224d2715e70122c96c5357860c1/gym_multigrid/multigrid.py#L223 it uses `random` instead of `self.np_random`. Can you try that if fixing it will solve your issue or not?

**Comment by miki-yuasa** [comment]
I fixed it, and the fix is available in the dev branch. Can you try it?

**Comment by Mgineer117** [comment]
@miki-yuasa Thanks Miki! It works now.

**Comment by miki-yuasa** [comment]
Sounds awesome! Now closing by #87
